language: 'python'
sudo: false
python:
  - "2.7.11"

env:
  global:
    - 'AWS_DEFAULT_REGION=us-east-1'
    - 'AWS_ACCESS_KEY_ID=AKIAJGARB35NA2OFFNYQ'
    - secure: "m/K72Fki3Ym5AqxxauCwwdN8elJUf4O9D04WFWR6KXeZC2ylVxLLx7fJpHgob549jJL23MBzXWj5CsI6ylSaBV2SqQ06tE5U4u6rLSW50goRuLLoHXFyNGEhVcC0bnheMNGDJjMjSRDiNiyDj2lwxqkT7yC1XPUq0tT/RBGNFTIyf+1IPyetXk2gtuITpZ9WG92+ATz2jenqRVh3wtpBO+RvvJSJcRSU536rZjojuS1I2cd7LZxNvLc1cbwtgFszB3GyHTx48gN5Zhwpa89M4a43FzPh/ZeEw6v4oISLp2jCKjy7jFVbp+Ug0VS7SmqhuEALBYgeQ+FNnARkYPaFYpLZBPiKGqhNlPX40xXguXZIu8l1cTqdztFmYUk1nNI1FKwppPBtRFN0gRGzUl2Er4300h9VtZ7J22nCzdSoqRQ2lbqddiO1qi7qjgEd25/5c3dg6GlhOyRtehHD5Y5ZYx/E+a4ZRL4DUjHnKSZfdc2K5/TRB5TByOLzuQJMgO5xG/G3KZSquWLZLK3Dxu0E15XuQM1q1dl+0VUJbILjEqAP/pFgN8vgVku8ytD0KlYYdV+kBYUIpVAs3ls/20IVm/2DoKCNd7lYF6IOjvsbu1lqedRoThfkE8pIAEOi/ZqXKqc6ym9c3hWDsUhkCXIa3AQe+B1pM34mOQdwNmPbS+E="

before_install:
  - 'pip install awscli'

install:
  - 'make install'

script:
  - 'make test'

after_success:
  - './env/bin/coveralls'

before_deploy:
  - 'make lambda'

deploy:
  - provider: 'script'
    script: '
      aws lambda
        update-function-code
        --function-name "tidycat-auth-backend-staging"
        --zip-file fileb://lambda.zip
        --publish'
    skip_cleanup: true
    on:
      repo: 'tidycat/auth-backend'
      branch: 'master'
  - provider: 'script'
    script: '
      aws lambda
        update-function-code
        --function-name "tidycat-auth-backend"
        --zip-file fileb://lambda.zip
        --publish'
    skip_cleanup: true
    on:
      repo: 'tidycat/auth-backend'
      tags: true
  - provider: 'releases'
    api_key:
      secure: "KZo2pYiN/Az5wy3QctQvWMGMdQSNJWkq5XH1JmtGQkIhD4YlKVZRCWwwNrTK5j7brHJbq0GSZ3LjW3qKxU2KPoOw/KEZgGPFkGOmcsJYD6siW/3VEAUOxh2T6T3NTyLR6CP5XsXZLhpDRngXUvXIodrpjmhORA7TdhUZXow6fePVDrWgcF9RZ3jgDiE8IJWwfrLoIZd1JhvNW2qTW8hrm4ue9wP8mXw0Lh1bYsOyJrSTo4qVRlodLnbvkZ4f9M3G0Qv8BXqLR3FCH6CsoKkWh6YrNZ8dptHcK585X691YSV/RRBQpAUQD/Fh3rgu4sBC5ACAz13XLsCY4JsXXrYQiRFUXcPeSiR8+ADJQTL3Ca2MhbVp+XMC5QjtWd4M7yYODki6b7HNNdPS6sHdmR4YNpb13We0p6rEl0Qt/EBK1qwssYPRNWXqFEGfWy4ZUC+z8dw1C+iLetXtpuUqZlNXhzX0j5ppfZTLuEY8waAlpV+qtCRQQAZkDXm6L0W+bQMR6cntebMI+D2IxbuaKgvk3azIjdqfm9n3wm3Fbj8JsAW3H99LwEyIYNPPvyd+QN8MwfPP1Qps6qRjBbZXdzDgRyWnV3qHLOOjq++OZjilZYfUDdsjwPKtTU0rIuoG3F/Q8/ShfWTsjtOTOuS25lydp12gqhQLG2P1e0iGEEW+E3Q="
    file: 'lambda.zip'
    skip_cleanup: true
    on:
      repo: 'tidycat/auth-backend'
      tags: true

notifications:
  email: false
  irc:
    channels:
      - secure: "b8ps6CVuinMwhqvFRZ3+nCyzxYQxX9j4qF1kC/yVRCCG/RdO3McmL2zzNKTBYWsa8hOO4GQOdVaqg4WDtuHbzHLJNUPgz8Is4x2PvDQdKZi+SotOYOqkSn/rzJZhVz2jMqvJr/+8ZQ356b7IetYZyFrlIcVuhUM3m3iBJ7RNz+H/MMwrHSghRbkS+9FC0ami89UP+Uhev9xbqxZ1lMvku/3e2aHu1K4bjwLIhnvDUq1Q55zikScYRR62xhIm+FqqNYfEWVI4uySjjD+8uLyfSFZ1/V1WvUR0YjG/AbFBNAFEIWGIiW2+EIrbN/pO/lP2hwI0Q4ZkB8gqNyIWbtb3A9u2RuOYqi6LxvDcO7OHUcY801Gl1dy8GCQxhPUX7979cmxEAt8GdyOl6Fi5ftSvqkiOBV9Pe3EoOlRHgK3cKtOyyws9AFcJ7cI1wcWnGledfuJblJjiqlPhtqy3+ybQF5nmkVteIX9/5V5CumK69odlCacRmJA3KAJoQvQTh9xOfmNKjTRZSzpX2AyhgZu//rQ7dBnDi1IgEwHe5gI7W+eC6VJWoUrw+leTe5KjcKgmV1Mcq8ZPdBz7cFBz4YG8K0g3QU5FBNxzmfcZ/+oLHrx9RUPyQwpCP+1mlA11Qy2LiTf+HyJHcJ5J6vOlBzTDATLUIwM9Ck8y4h7x6cuQ+1s="
    on_success: "change"
    on_failure: "change"
